GET http://localhost:5000/product/
###
POST http://localhost:5000/product
Content-Type: application/json

{
    "product_sku": "1234",
    "product_name": "Diesel Generator",
    "quantity": 5,
    "cost_price": 234,
    "sales_price": 1500
}

###

DELETE http://localhost:5000/inventory/654b9cf55e36daf19948ed68

###
PATCH http://localhost:5000/inventory/654ba1053c6523b008269677
Content-Type: application/json

{
    "product_sku": "KARLOSLAZARO",
    "product_name": "KARLOS",
    "quantity": 124,
    "cost_price": 12345,
    "sales_price": 500
}


###
POST http://localhost:4000/api/sales/
Content-Type: application/json 
{
    "customerName": "Karlos",
    "productID": "655210a967ddb5cdfd0ab1fc",
    "quantitySold": 1,
 

}

###
GET http://localhost:4000/api/sales/

###
GET http://localhost:4000/sales/