GET http://localhost:5000/api/product/
###
POST http://localhost:5000/inventory
Content-Type: application/json

{
    "product_sku": "1234karlos",
    "product_name": "Welding Machine",
    "quantity": 12,
    "cost_price": 2000,
    "sales_price": 5000
}

###

DELETE http://localhost:5000/inventory/654b9cf55e36daf19948ed68

###
PATCH http://localhost:5000/inventory/654ba1053c6523b008269677
Content-Type: application/json

{
    "product_sku": "KARLOSLAZARO",
    "product_name": "KARLOS",
    "quantity": 124,
    "cost_price": 12345,
    "sales_price": 500
}